<!--from Bootstrap Carousel: http://www.w3schools.com/bootstrap/bootstrap_ref_js_carousel.asp-->
    <div id="indexCarousel" class="carousel slide" data-ride="carousel"> 
                <ol class="carousel-indicators">
                    <li data-target="#indexCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#indexCarousel" data-slide-to="1"></li>
                    <li data-target="#indexCarousel" data-slide-to="2"></li>
                </ol>

                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                      <img src="images/nas1.jpg" alt="Nas">
                      <div class="carousel-caption">
                        <h3>Hip hop</h3> 
                       <p>Nas</p>
                      </div>
                    </div>

                    <div class="item">
                      <img src="images/madeon.jpg" alt="Madeon">
                      <div class="carousel-caption">
                        <h3>EDM</h3>
                        <p>Madeon</p>
                      </div>
                    </div>

                    <div class="item">
                      <img src="images/aphex-twin.jpg" alt="Aphex-Twin">
                      <div class="carousel-caption">
                        <h3>IDM</h3>
                        <p>Aphex-Twin</p>
                      </div>
                    </div>

                     <!-- Left and right controls -->
                      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                      </a>
                      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                      </a>

                </div><!--carousel-inner-->


                        
            </div><!--Carousel-->